language: java

before_install:
  - openssl aes-256-cbc -K $encrypted_35e5dc022c67_key -iv $encrypted_35e5dc022c67_iv -in secring.encrypted.gpg -out secring.gpg -d

deploy:
  provider: script
  script: ./gradlew uploadArchives
  skip_cleanup: true
  on:
    tags: true